In [247]:
import numpy as np
import math
import pandas as pd
import copy

## Questão 2

In [248]:
dataset = pd.read_csv('lista4db.csv', sep=",")
X = dataset.iloc[:, 1:-1].values
Y = dataset.iloc[:, -1:].values

In [249]:
def apply_to_each_element(mtx, fn):
    new_mtx = copy.copy(mtx)
    shape_x = mtx.shape[0]
    shape_y = mtx.shape[1]
    for i in range(shape_x):
        for j in range(shape_y):
            new_mtx[i, j] = fn(new_mtx[i, j])
    return new_mtx

In [250]:
def convert_to_float(el):
    new_el = comma_to_dot(el)
    return float(new_el)

In [251]:
def comma_to_dot(str_el):
    return str_el.replace(',', '.')

In [252]:
X = apply_to_each_element(X, convert_to_float)
Y = apply_to_each_element(Y, convert_to_float)

### 2.1

In [253]:
mean_X = np.mean(X, axis=0)
mean_Y = np.mean(Y, axis=0)

In [254]:
def dp(random_sample):
    mean = np.mean(random_sample, axis=0)
    sum_arg = [np.square(x - mean) for x in random_sample]
    num = sum(sum_arg)
    den = random_sample.shape[0] - 1
    return math.sqrt(num / den)

dp_X = np.apply_along_axis(dp, 0, X)
dp_Y = np.apply_along_axis(dp, 0, Y)

In [255]:
data = [np.concatenate((mean_X, mean_Y)), np.concatenate((dp_X, dp_Y))]
pd.DataFrame(data, index=["Média", "Desvio Padrão"], columns=["X1", "X2", "X3", "X4", "Y"])

                     X1        X2        X3        X4         Y
Média          9.660833 -0.978056  2.086667  4.915833  3.438056
Desvio Padrão  2.087186  1.082111  0.611303  1.402456  1.845095

In [256]:
def normalize(el, mean, dp):
    return (el - mean) / dp

norm_X1 = apply_to_each_element(X[:, 0:1], lambda el : normalize(el, mean_X[0], dp_X[0]))
norm_X2 = apply_to_each_element(X[:, 1:2], lambda el : normalize(el, mean_X[1], dp_X[1]))
norm_X3 = apply_to_each_element(X[:, 2:3], lambda el : normalize(el, mean_X[2], dp_X[2]))
norm_X4 = apply_to_each_element(X[:, 3:4], lambda el : normalize(el, mean_X[3], dp_X[3]))

norm_X = np.concatenate((norm_X1, norm_X2, norm_X3, norm_X4), axis=1)
norm_Y = apply_to_each_element(Y, lambda el : normalize(el, mean_Y[0],dp_Y[0]))

norm_data = np.concatenate((norm_X, norm_Y), axis=1)
pd.DataFrame(norm_data, columns=["X1", "X2", "X3", "X4", "Y"])

           X1        X2         X3          X4          Y
0   -0.925089 -0.547027     -1.156   -0.253722   0.640587
1   -0.225583 -0.759575    1.23234   -0.239461  -0.670998
2   -0.163298 -0.251309   0.888812     1.22226  0.0281527
3     -1.0832  0.312404   -1.00877    0.908525   0.922416
4     1.35549  0.839152    -1.6304    -1.41597  -0.107342
5   -0.709488  -0.95364   0.627076    0.680354   0.418376
6    0.042721  -1.40646  -0.992416   0.0457531   0.667686
7   -0.263912  -1.78535    1.37957    0.765918  -0.280774
8   0.0283476 -0.731851   -1.23779    -1.10223  0.0823505
9     -1.2461  0.414057   0.398057    0.159839   0.429216
10   -2.42951 -0.288274    1.06876    0.288185   -0.15612
11   -0.25433  0.626604    1.19962     1.36487   0.125709
12    0.45955  0.645087   -1.69583    0.651833    2.99819
13    1.64775 -0.279033    1.41228    -1.19493   -2.30777
14    1.79149 -0.205103   -1.33594    -1.99353   -1.34847
15   -1.34671 -0.639439   0.103604     1.52887   0.667686
16    1.65254   1.10715    1.11783   -0.617369   -1.70618
17 -0.0339372   1.25501   0.986963   -0.310764  -0.698097
18   0.895544  0.857634   0.807019   -0.645891  -0.974506
19   -0.55138   1.63389  -0.190849 -0.00415937   0.754403
20   0.267905  -1.85004    0.90517   0.0457531   0.537612
21  -0.110595 -0.269792 -0.0436227   -0.360677   0.190746
22   0.608076 -0.297515  -0.223566   -0.118245  -0.508405
23  0.0283476 -0.962881    0.36534   -0.702934  -0.660159
24    1.30758 -0.315998  -0.518019    0.295315  -0.557183
25   0.152917  -1.60976  -0.190849    0.937047   0.548451
26   -1.09757    1.3659   -0.73068  -0.0112897   0.841119
27    1.63338 -0.297515   -1.27051    -2.39283   -1.45145
28   0.435594   1.03322    1.15055    0.259664   -1.00702
29  -0.354944  -1.32329  -0.485302       1.044   0.456315
30     1.2453 -0.657922   0.643434    -1.23771   -1.40267
31   -1.04008  0.682051   0.872453     1.57878   0.694785
32  -0.283077  0.811428   0.757944      1.7713   0.862798
33   -1.32755  0.931564   -1.45045  -0.0184201    1.23134
34  -0.450766   1.14411   -1.13964    0.302446   0.683945
35   0.344563   1.77251   -0.61617    -1.23058  0.0552516

### 2.2

In [264]:
def r(x, y):    
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    
    num = sum([np.mean((x[i] - mean_x) * (y[i] - mean_y)) for i in range(x.shape[0])])
    den_x = math.sqrt(sum([(el_x - mean_x) ** 2 for el_x in x]))
    den_y = math.sqrt(sum([(el_y - mean_y) ** 2 for el_y in y]))
    return num / (den_x * den_y)

values = np.concatenate((X, Y), axis=1)

def R(mtx):
    num_of_entries = mtx.shape[1]
    R = np.zeros((num_of_entries, num_of_entries), dtype=float)
    
    for i in range(num_of_entries):
        for j in range(num_of_entries):
            R[i, j] = r(mtx[:, i], mtx[:, j])
    return R

header = ["X1", "X2", "X3", "X4", "Y"]
corr = R(values)
pd.DataFrame(corr, index=header, columns=header)

          X1        X2        X3        X4         Y
X1  1.000000 -0.020136 -0.067912 -0.615565 -0.605025
X2 -0.020136  1.000000 -0.114622 -0.074094  0.083112
X3 -0.067912 -0.114622  1.000000  0.299956 -0.425429
X4 -0.615565 -0.074094  0.299956  1.000000  0.586570
Y  -0.605025  0.083112 -0.425429  0.586570  1.000000

In [272]:
num_of_samples = X.shape[0]
criteria_y = 2 / math.sqrt(num_of_samples)
criteria_y

0.3333333333333333

array([[1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 1.],
       [1., 0., 1., 1., 1.]])

AttributeError: module 'math' has no attribute 'absolute'